// src/routes/Navigation.svelte
<script>
    import { page } from "$app/stores";
    import { assetsBasePath } from "../lib/path";
    import { base } from "$app/paths";
</script>

<nav>
	<div class="container">
		<img src="{assetsBasePath}images/Logo.png" class="logo" alt="logo" />
		<div class="nav-links">
			<li aria-current={$page.url.pathname === "/" ? "page" : undefined}>
				<a href="{base}/">home.</a>
			</li>
			<li aria-current={$page.url.pathname === "/about" ? "page" : undefined}>
				<a href="{base}/work">work.</a>
			</li>
			<li aria-current={$page.url.pathname.startsWith("/sverdle") ? "page" : undefined}>
				<a href="{base}/about">about.</a>
			</li>
		</div>
	</div>
</nav>

<style>
    .container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 1rem;
    }
    .nav-links {
        display: flex;
        gap: 1rem;
    }
	.nav-links li {
        list-style-type: none;
	}
    .nav-links a {
        text-decoration: none;
        padding: 0.25rem 0.75rem;
        color: #ffffff;
        font-weight: 900;
    }
    .nav-links a:hover {
        outline: 0.2rem solid #ffffff;
    }
    .nav-links a:focus {
        outline: none;
    }
    .logo {
        width: 5rem;
        height: 7rem;
    }
</style>

// src/components/Navigation.jsx
import React from 'react';
import styled from 'styled-components';

const NavigationContainer = styled.nav`
    background-color: #12292B; 
    padding: 10px; 
    display: flex;
    justify-content: space-between;
    align-items: center;
`;

const Logo = styled.div`
    color: #FFFFFF;
    font-weight: bold;
    font-size: 10px;
`;

const Links = styled.ul`
    list-style: none; 
    display: flex;
    margin: 0;
    padding: 0;

    li {
        margin-right: 10px;
        a {
            color: #FFFFFF;
            text-decoration: none;
        }
    }
`;

function Navigation() {
    return (
        <NavigationContainer>
            <Logo>
                <pre>
                    {String.raw`          
      __      __   __     __   __     ______     ______     _____     ______    
     /\ \    /\ "-.\ \   /\ "-.\ \   /\  ___\   /\  __ \   /\  __-.  /\  ___\    
    _\_\ \   \ \ \-.  \  \ \ \-.  \  \ \ \____  \ \ \/\ \  \ \ \/\ \ \ \  __\   
   /\_____\   \ \_\\"\_\  \ \_\\"\_\  \ \_____\  \ \_____\  \ \____-  \ \_____\ 
   \/_____/    \/_/ \/_/   \/_/ \/_/   \/_____/   \/_____/   \/____/   \/_____/     
                    `}       
                </pre>
            </Logo>
            <Links>
                <li><a href='../Intro' onClick={() => navigateTo('../Intro')}>home.</a></li>
                <li><a href='../Project' onClick={() => navigateTo('../Project')}>projects.</a></li>
                <li><a href='../Contact' onClick={() => navigateTo('../Contact')}>contact.</a></li>
                <li><a href='../About' onClick={() => navigateTo('../About')}>about.</a></li>
            </Links>
        </NavigationContainer>
    )
}

export default Navigation;
